version: '3.1'

volumes:
  saved-data:
  web-server-keys:

services:
  web-server:
    build:
      dockerfile: ./web-server.Dockerfile
    image: web-server
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - saved-data:/data
      - web-server-keys:/keys

  file-strip:
    build:
      dockerfile: ./file-watcher.Dockerfile
    image: file-strip
    restart: always
    environment:
      DATA_FOLDER: /data
      MAX_FILE_NUMBER: 30
      SLEEP_INTERVAL: 3600
    volumes:
      - saved-data:/data
